// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFx_apd70Er-5P5orPGannAIyHmIPiGP0',
    appId: '1:230410219102:web:03b842c76f7f64c96fcecf',
    messagingSenderId: '230410219102',
    projectId: 'crunchy-hot',
    authDomain: 'crunchy-hot.firebaseapp.com',
    storageBucket: 'crunchy-hot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8OeQl_ISZC3QxoXO7Qw_p6_1zWGlPU0I',
    appId: '1:230410219102:android:bde7cc2c49eb50e56fcecf',
    messagingSenderId: '230410219102',
    projectId: 'crunchy-hot',
    storageBucket: 'crunchy-hot.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3N1ifDMFV6qzeuu22emXInGDdSeE1hHI',
    appId: '1:230410219102:ios:dea64576473f954d6fcecf',
    messagingSenderId: '230410219102',
    projectId: 'crunchy-hot',
    storageBucket: 'crunchy-hot.firebasestorage.app',
    iosBundleId: 'com.example.crunchyHot',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3N1ifDMFV6qzeuu22emXInGDdSeE1hHI',
    appId: '1:230410219102:ios:dea64576473f954d6fcecf',
    messagingSenderId: '230410219102',
    projectId: 'crunchy-hot',
    storageBucket: 'crunchy-hot.firebasestorage.app',
    iosBundleId: 'com.example.crunchyHot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFx_apd70Er-5P5orPGannAIyHmIPiGP0',
    appId: '1:230410219102:web:ebc962126462e5e26fcecf',
    messagingSenderId: '230410219102',
    projectId: 'crunchy-hot',
    authDomain: 'crunchy-hot.firebaseapp.com',
    storageBucket: 'crunchy-hot.firebasestorage.app',
  );
}
