import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:provider/provider.dart';

import 'firebase_options.dart';

import 'controllers/auth_controller.dart';
import 'controllers/cart_controller.dart';
import 'controllers/favourites_controller.dart';
import 'controllers/home_controller.dart';
import 'controllers/loyalty_controller.dart';
import 'controllers/menu_controller.dart' as ch;
import 'controllers/offers_controller.dart';
import 'controllers/orders_controller.dart';
import 'controllers/search_controller.dart';
import 'screens/splash_screen.dart';
import 'services/api_client.dart';
import 'services/app_config_service.dart';
import 'services/app_prefs.dart';
import 'services/address_service.dart';
import 'services/auth_service.dart';
import 'services/branch_service.dart';
import 'services/cart_service.dart';
import 'services/catalog_service.dart';
import 'services/coupons_service.dart';
import 'services/favourites_service.dart';
import 'services/push_notifications_service.dart';
import 'services/loyalty_service.dart';
import 'services/order_service.dart';
import 'theme/theme.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await AppPrefs.init();
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Firebase must be initialised before any FCM handler is wired.
  // DefaultFirebaseOptions is generated by `flutterfire configure` and
  // lives in lib/firebase_options.dart.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Push service is a plain object (no ChangeNotifier). Built here so we can
  // call `init()` before runApp — background handler + permission prompt need
  // to run before the first frame paints.
  final prefs        = AppPrefs.instance;
  final apiClient    = ApiClient(prefs);
  final pushService  = PushNotificationsService(apiClient);
  await pushService.init();

  // Live public config (delivery fee, hours, …). Fire-and-forget so a slow
  // network doesn't block boot — CartService falls back to 5000 SYP until
  // the first payload lands, then CartController refreshes automatically.
  final appConfig = AppConfigService(apiClient);
  unawaited(appConfig.load());

  runApp(CrunchyHotApp(
    apiClient:   apiClient,
    appConfig:   appConfig,
    pushService: pushService,
  ));
}

class CrunchyHotApp extends StatefulWidget {
  const CrunchyHotApp({
    super.key,
    required this.apiClient,
    required this.appConfig,
    required this.pushService,
  });

  final ApiClient apiClient;
  final AppConfigService appConfig;
  final PushNotificationsService pushService;

  @override
  State<CrunchyHotApp> createState() => _CrunchyHotAppState();
}

class _CrunchyHotAppState extends State<CrunchyHotApp> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // App came back to foreground → re-pull live config so a mid-session
    // admin edit to `business.delivery_fee_syp` propagates before the user
    // sees Cart/Checkout again.
    if (state == AppLifecycleState.resumed) {
      unawaited(widget.appConfig.load());
    }
  }

  @override
  Widget build(BuildContext context) {
    final prefs  = AppPrefs.instance;
    final client = widget.apiClient;

    return MultiProvider(
      providers: [
        // ─── HTTP transport ───
        Provider<ApiClient>(create: (_) => client),
        Provider<PushNotificationsService>.value(value: widget.pushService),

        // ─── Live public config (delivery fee, hours, …) ───
        ChangeNotifierProvider<AppConfigService>.value(value: widget.appConfig),

        // ─── Services (stateless singletons) ───
        Provider<AuthService>   (create: (_) => AuthService(prefs, client)),
        Provider<CatalogService>(create: (_) => CatalogService(client)),
        Provider<CartService>   (create: (ctx) => CartService(client, ctx.read<AppConfigService>())),
        Provider<OrderService>  (create: (_) => OrderService(client)),
        Provider<LoyaltyService>(create: (_) => LoyaltyService(client)),
        Provider<BranchService> (create: (_) => BranchService(client)),
        Provider<AddressService>(create: (_) => AddressService(client)),
        Provider<FavouritesService>(create: (_) => FavouritesService(client)),
        Provider<CouponsService>(create: (_) => CouponsService(client)),

        // ─── Controllers (ChangeNotifiers) ───
        ChangeNotifierProvider<AuthController>(
          create: (ctx) => AuthController(ctx.read<AuthService>(), prefs),
        ),
        ChangeNotifierProvider<CartController>(
          create: (ctx) => CartController(
            ctx.read<CartService>(),
            ctx.read<AppConfigService>(),
            prefs,
          ),
        ),
        ChangeNotifierProvider<CatalogSearchController>(
          create: (ctx) => CatalogSearchController(ctx.read<CatalogService>(), prefs),
        ),
        ChangeNotifierProvider<HomeController>(
          lazy: true,
          create: (ctx) => HomeController(ctx.read<CatalogService>()),
        ),
        ChangeNotifierProvider<ch.MenuController>(
          lazy: true,
          create: (ctx) => ch.MenuController(ctx.read<CatalogService>()),
        ),
        ChangeNotifierProvider<OrdersController>(
          lazy: true,
          create: (ctx) => OrdersController(ctx.read<OrderService>()),
        ),
        ChangeNotifierProvider<LoyaltyController>(
          lazy: true,
          create: (ctx) => LoyaltyController(ctx.read<LoyaltyService>()),
        ),
        ChangeNotifierProvider<FavouritesController>(
          lazy: true,
          create: (ctx) => FavouritesController(ctx.read<FavouritesService>()),
        ),
        ChangeNotifierProvider<OffersController>(
          lazy: true,
          create: (ctx) => OffersController(
            ctx.read<CatalogService>(),
            ctx.read<CouponsService>(),
          ),
        ),
      ],
      child: MaterialApp(
        title: 'كرانشي هت',
        debugShowCheckedModeBanner: false,
        theme: ChTheme.light(),

        // Root NavigatorKey shared with PushNotificationsService so tapped
        // notifications can route the app from outside the widget tree.
        navigatorKey: PushNotificationsService.rootNavigatorKey,

        // --- Localization / RTL ---
        locale: const Locale('ar'),
        supportedLocales: const [Locale('ar'), Locale('en')],
        localizationsDelegates: const [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        builder: (context, child) => Directionality(
          textDirection: TextDirection.rtl,
          child: child ?? const SizedBox.shrink(),
        ),

        home: const SplashScreen(),
      ),
    );
  }
}
